spring:
  profiles:
    default: local

  h2:
    console:
      enabled: true
  datasource:
    # url: jdbc:h2:mem:~/cafeKioskApplication
    url: jdbc:h2:tcp://localhost/~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey: AKIA4JHZUL4EY4NEHJUT
      secretKey: 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
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: kangmin-s3-bucket
      endPoint: https://s3.ap-northeast-2.amazonaws.com
      folder: storage

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test # h2 in-memory-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace