spring:
  profiles:
    default: prod

  h2:
    console:
      enabled: true
  datasource:
    # url: jdbc:h2:mem:~/cafeKioskApplication
    url: jdbc:h2:tcp://localhost/~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
  jpa:
    hibernate:
      ddl-auto: none

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey: ${aws.s3.accessKey}
      secretKey: ${aws.s3.secretKey}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: kangmin-s3
      endPoint: https://s3.ap-northeast-2.amazonaws.com
      folder: storage

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test # h2 in-memory-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: never

logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${aws.rds.mysql.url}
    username: ${aws.rds.mysql.username}
    password: ${aws.rds.mysql.password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
